### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "mysecretpassword"
}

### reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "test@example.com",
  "previousPassword": "mysecretpassword",
  "newPassword": "newsecretpassword2"
}

### create history
POST http://localhost:3000/history
Content-Type: application/json

{
  "device": "mq2",
  "type": "temperature",
  "value": 22.5
}

### get history by id
GET http://localhost:3000/history/PLACEHOLDER_ID

### get history by type (paginated)
GET http://localhost:3000/history/type/temperature

### get history by type and date (paginated - standard YYYY-MM-DD structure)
GET http://localhost:3000/history/type/temperature/date/2026-04-06?page=1&limit=5

